// <auto-generated />
using System;
using Assets.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Assets.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200407103106_AddBrokerId")]
    partial class AddBrokerId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Assets.Repositories.Entities.AssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnName("accuracy")
                        .HasColumnType("integer");

                    b.Property<string>("BrokerId")
                        .IsRequired()
                        .HasColumnName("broker_id")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnName("is_disabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("Assets.Repositories.Entities.AssetPairEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Accuracy")
                        .HasColumnName("accuracy")
                        .HasColumnType("integer");

                    b.Property<string>("BaseAssetId")
                        .IsRequired()
                        .HasColumnName("base_asset_id")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("BrokerId")
                        .IsRequired()
                        .HasColumnName("broker_id")
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnName("is_disabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarketOrderPriceThreshold")
                        .HasColumnName("market_order_price_threshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxOppositeVolume")
                        .HasColumnName("max_opposite_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxVolume")
                        .HasColumnName("max_volume")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinVolume")
                        .HasColumnName("min_volume")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Modified")
                        .HasColumnName("modified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QuotingAssetId")
                        .IsRequired()
                        .HasColumnName("quoting_asset_id")
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("BaseAssetId");

                    b.HasIndex("QuotingAssetId");

                    b.ToTable("asset_pairs");
                });

            modelBuilder.Entity("Assets.Repositories.Entities.AssetPairEntity", b =>
                {
                    b.HasOne("Assets.Repositories.Entities.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("BaseAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Assets.Repositories.Entities.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("QuotingAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
